Suppress errors on make clean
Do not show the error messages when running make clean more than once in
a row, since they are normally false alarms.

Fixes the output:

    $ make clean
    ...
    $ make clean
    podman pod kill afsbotcfg
    Error: no pod with name or ID afsbotcfg found: no such pod
    make: [Makefile:143: clean] Error 125 (ignored)
    podman pod rm afsbotcfg
    Error: no pod with name or ID afsbotcfg found: no such pod
    make: [Makefile:144: clean] Error 1 (ignored)
    podman volume rm afsbotcfg
    Error: no volume with name "afsbotcfg" found: no such volume
    make: [Makefile:145: clean] Error 1 (ignored)
    rm -rf .pod