Revert "Rewrite build status messages"
This reverts commit a5cf6f508d880a6a06dcdd150dfa81716909e642.

Fails with an exception. Should have been tested better with molecule
before deploying.

2023-06-02 10:19:58-0400 [-] releaseLocks(<WatchedWorker 'wins2019-amd64'>): []
2023-06-02 10:20:54-0400 [-] Unhandled error in Deferred:
2023-06-02 10:20:54-0400 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/buildbot/reporters/gerrit.py", line 341, in buildsetComplete
	    self.sendBuildSetSummary(buildset, builds)
	  File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
	    return _cancellableInlineCallbacks(gen)
	  File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	--- <exception caught here> ---
	  File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/buildbot/reporters/gerrit.py", line 370, in sendBuildSetSummary
	    self.summaryArg)
	  File "/home/buildbot/.venv/buildbot/lib64/python3.6/site-packages/afsbotcfg/gerrit.py", line 78, in summaryCB
	    "Passed" if verified == 1 else "Failed",
	builtins.TypeError: not enough arguments for format string