Suppress gcc format-truncation errors on new fedora workers
Suppress warnings-to-errors for format-truncation since some of
them are in imported code,

Example:

  In file included from ticket5.c:83:
  v5der.c: In function ‘_rxkad_v5__heim_time2generalizedtime’:
  v5der.c:1168:40: error: ‘%02d’ directive output may be truncated writing between 2 and 11 bytes into a region of size between 0 and 10 [-Werror=format-truncation=]
     snprintf (s->data, len + 1, "%02d%02d%02d%02d%02d%02dZ",